name: CI

on:
  issues:
    types: [opened]

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: pass env variable to python
        env: 
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          python data/store_issue.py
          python data/updater.py

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "action issue"
          git push
