name: CI

on:
  #push:
  #  branches: [ master ]
  
  issue_comment:
    types: [created, deleted]

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Modifiy the specific files using scripts
        run: |
            python helloworld.py ${{ github.event.comment.body }}

      - name: GitHub Event
        run: |
          cat << 'EOF'
            ${{ github.event.comment.body }}
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "allisonsampaio"
          git config --global user.email "allisonsampaixo@gmail.com"

          git add -A
          git commit -m "commit message"
          git push
